### ISSUE TITLE
Syntax highlighting breaks for one-liner if/tell statements

### ISSUE THREAD

**Issue by caleb531** [franzheidl/atom-applescript#5] opened 2015-04-13 20:59 UTC
Hi,

I'm writing to report an interesting issue with the package that I discovered recently. Apparently, if an AppleScript file contains a one-liner `if`/`tell` statement (and thus lacks an `end` statement), the next `end` statement (in this case, of the containing handler) will appear white and unhighlighted (when it should be highlighted as blue).

Here's a basic example to demonstrate this bug:

```applescript
on foo()
	if true then display dialog "True!"
end foo
```

Could you please update the package to account for this case?

Thanks,
Caleb

**Comment by franzheidl** [comment] 2015-04-15 21:35
Hi,

can't reproduce this with atom-applescript 0.1.0 using Railscast theme:

![screenshot](https://cloud.githubusercontent.com/assets/1186274/7169669/fd9232ec-e3c7-11e4-8935-92bd29edc831.png)

Are you sure this isn't related to the theme you're using?
Closing this for now, feel free to re-open if issue persists.

**Closed by franzheidl** 2015-04-15 21:35 UTC

**Comment by caleb531** [comment] 2015-04-15 22:15
Oh, how interesting. The issue occurs when I use **Atom Dark**, **One Dark**, or **Base16 Tomorrow Dark** themes (*or* their light equivalents), all of which are pre-packaged with Atom (perhaps that's no coincidence, then). However, when I use a third-party theme such as **Railscast** or **Monokai**, the syntax is highlighted correctly. I think it's time for me to try something new. ;)

Apologies for the false alarm. Carry on.
